### create studentCourse
POST localhost:8080/student_course/create
Content-Type: application/json

{
  "student_id":10,
  "course_id":3,
  "mark": 3

}

### update studentCourse
PUT localhost:8080/student_course/update/10
Content-Type: application/json

{
  "student_id": 10,
  "course_id": 3,
  "mark": 4
}

### get by id
GET localhost:8080/student_course/get/10
### get list
GET localhost:8080/student_course/list
### get by id with detail ???
GET localhost:8080/student_course/getWithDetail/10
### get student mark day
GET localhost:8080/student_course/getMark?s_id=10&date=2023-04-06

### get student mark between days
GET localhost:8080/student_course/getMarkBetweenDays?s_id=10&f_date=2023-04-05&t_date=2023-04-08
### get all mark order by created date desc
GET localhost:8080/student_course/getMarkAll?s_id=10
### get all mark course order by cr desc
GET localhost:8080/student_course/getAllMarkCourse?s_id=10&c_id=1
### get last mark
GET localhost:8080/student_course/lastMark?s_id=10
### get first mark
GET localhost:8080/student_course/firstMark?s_id=10
### get top 3 mark
GET localhost:8080/student_course/top3?s_id=10

### get first mark course
GET localhost:8080/student_course/firstMarkCourse?s_id=10&c_id=1

### get max mark
GET localhost:8080/student_course/maxMarkCourse?s_id=10&c_id=1

### get avg mark
GET localhost:8080/student_course/avgMark?s_id=10